name: copilot-build-backend

on:
  workflow_call:
    outputs:
      artifact:
        description: "The name of the uploaded artifact."
        value: ${{jobs.web-api.outputs.artifact}}

permissions:
  contents: read

jobs:
  web-api:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { dotnet: "6.0", configuration: Release, os: windows-latest }

    runs-on: ${{ matrix.os }}

    env:
      NUGET_CERT_REVOCATION_MODE: offline

    outputs:
      artifact: ${{steps.artifactoutput.outputs.artifactname}}

    steps:
      - uses: actions/checkout@v3
        with:
          clean: true

      - name: Package Copilot Chat WebAPI
        run: |
          deploy\package-webapi.ps1 -Configuration Release -DotnetFramework net6.0 -TargetRuntime win-x64 -OutputDirectory ${{ github.workspace }}\deploy

      - name: Set version tag
        id: versiontag
        run: |
          $VERSION_TAG="$(Get-Date -Format "MMddHHmmss")"
          echo $VERSION_TAG
          Write-Output "versiontag=$VERSION_TAG" >> $env:GITHUB_OUTPUT

      - name: Upload package to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: copilotchat-webapi-${{ steps.versiontag.outputs.versiontag }}
          path: ${{ github.workspace }}\deploy\out\webapi.zip

      - name: "Set outputs"
        id: artifactoutput
        run: Write-Output "artifactname=copilotchat-webapi-${{ steps.versiontag.outputs.versiontag }}" >> $env:GITHUB_OUTPUT
