name: copilot-build-images

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build-and-push-image:
    name: Build and push images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - file: ./docker/webapi/Dockerfile
            image: ${{ github.repository }}-webapi
            build-args: |

          # Only build nginx image
          # - file: ./docker/webapp/Dockerfile
          #   image: ${{ github.repository }}-webapp
          #   build-args: |

          - file: ./docker/webapp/Dockerfile.nginx
            image: ${{ github.repository }}-webapp-nginx
            build-args: |

          # Excluded for now
          # - file: ./docker/plugins/web-searcher/Dockerfile
          #   image: ${{ github.repository }}-web-searcher
          #   build-args: |

          # Excluded for now
          # - file: ./docker/memorypipeline/Dockerfile
          #   image: ${{ github.repository }}-memorypipeline
          #   build-args: |

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.REGISTRY }}/${{ matrix.image }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.file }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: ${{ matrix.build-args }}
