name: copilot-deploy-plugins

on:
  workflow_call:
    inputs:
      ARTIFACT_NAME:
        required: true
        type: string
      ENVIRONMENT:
        required: true
        type: string
      DEPLOYMENT_NAME:
        required: true
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  plugins:
    environment: ${{inputs.ENVIRONMENT}}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { dotnet: "6.0", configuration: Release, os: ubuntu-latest }

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          clean: true

      - name: Install Azure CLI
        run: |
          sudo apt update && sudo apt-get install curl -y
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - uses: actions/download-artifact@v4
        with:
          name: ${{inputs.ARTIFACT_NAME}}
          path: "${{ github.workspace }}/${{inputs.ARTIFACT_NAME}}"

      - name: "Display downloaded content"
        run: ls -R
        working-directory: "${{ github.workspace }}/${{inputs.ARTIFACT_NAME}}"

      - name: "Azure login"
        uses: azure/login@v2
        with:
          client-id: ${{vars.AZURE_GITHUB_ACCESS_APP_ID}}
          tenant-id: ${{vars.AZURE_GITHUB_ACCESS_TENANT_ID}}
          subscription-id: ${{vars.AZURE_GITHUB_ACCESS_SUB_ID}}
          enable-AzPSSession: false

      - name: "Deploy"
        run: |
          scripts/deploy/deploy-plugins.sh \
            --deployment-name ${{inputs.DEPLOYMENT_NAME}} \
            --subscription ${{vars.AZURE_SUBSCRIPTION_ID}} \
            --resource-group ${{vars.CC_DEPLOYMENT_GROUP_NAME}} \
            --packages "${{ github.workspace }}/${{inputs.ARTIFACT_NAME}}"
