name: copilot-deploy-backend

on:
  workflow_call:
    inputs:
      ARTIFACT_NAME:
        required: true
        type: string
      ENVIRONMENT:
        required: true
        type: string
      DEPLOYMENT_NAME:
        required: true
        type: string
    outputs:
      backend-host:
        description: "Host to which backend is deployed"
        value: ${{jobs.webapi.outputs.backend-host}}

permissions:
  contents: read
  id-token: write

jobs:
  webapi:
    environment: ${{inputs.ENVIRONMENT}}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { dotnet: "6.0", configuration: Release, os: ubuntu-latest }
    # Map the job output to step output
    outputs:
      backend-host: ${{steps.app-name.outputs.backend-host}}

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            scripts

      - uses: actions/download-artifact@v4
        with:
          name: ${{inputs.ARTIFACT_NAME}}
          path: "${{ github.workspace }}/${{inputs.ARTIFACT_NAME}}"

      - name: "Display downloaded content"
        run: ls -R
        working-directory: "${{ github.workspace }}/${{inputs.ARTIFACT_NAME}}"

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{vars.AZURE_GITHUB_ACCESS_APP_ID}}
          tenant-id: ${{vars.AZURE_GITHUB_ACCESS_TENANT_ID}}
          subscription-id: ${{vars.AZURE_GITHUB_ACCESS_SUB_ID}}
          enable-AzPSSession: false

      - name: Get app name
        id: app-name
        run: |
          WEB_APP_NAME=$(az deployment group show --name ${{inputs.DEPLOYMENT_NAME}} --resource-group ${{vars.CC_DEPLOYMENT_GROUP_NAME}} --output json | jq -r '.properties.outputs.webapiName.value')
          echo "AZURE_WEBAPP_NAME=$WEB_APP_NAME" >> $GITHUB_ENV
          echo "backend-host=$WEB_APP_NAME" >> $GITHUB_OUTPUT

      - name: Enable Run From Package
        uses: azure/CLI@v2
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az webapp config appsettings set --resource-group ${{vars.CC_DEPLOYMENT_GROUP_NAME}} --name ${{ env.AZURE_WEBAPP_NAME }} --settings WEBSITE_RUN_FROM_PACKAGE="1" -o none

      - name: "Deploy"
        run: |
          scripts/deploy/deploy-webapi.sh -p "${{ github.workspace }}/${{inputs.ARTIFACT_NAME}}/webapi.zip" -d ${{inputs.DEPLOYMENT_NAME}} -s ${{vars.AZURE_SUBSCRIPTION_ID}} -rg ${{vars.CC_DEPLOYMENT_GROUP_NAME}} --skip-app-registration
